[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dansar"
version = "0.1.0"
description = "Utilities for SAR workflows."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "requests",
    "asf-search",
    "rasterio",
    "earthengine-api",
    "google-cloud-storage",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
infer-uavsar-paths = "dansar.uavsar.infer_uavsar_paths:main"
download-uavsar = "dansar.uavsar.download_uavsar:main"
annotation2header = "dansar.uavsar.ann2envi_header:main"
make-tiff = "dansar.uavsar.make_tiff:main"
make-asf-session = "dansar.utils.make_asf_session:main"
